remote_theme: thedevslot/WhatATheme

# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

# Title of the Site
title: CCRMA MIR Workshops
# Description of the Site
description: Course materials for the Stanford CCRMA series
# URL of Image of the Site
site-image: /ccrma-mir/assets/images/home.JPG
# Keywords of the Site
site-keywords: Music, Information Retrival, MIR, Deep Learning, Signal Processing, Stanford 
# URL for the Image of custom Favicon
favicon-url: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDc2JCYxJx8fLT0tMTU3Ojo6Iys/RD84OjQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Ny03Nzc3Nzc3Nzc3Nzc3Nzc0MzcrNzc3Nzc3Nzc1LzU3Nys3Nzc1NzU3Nys3N//AABEIACAAHwMBIgACEQEDEQH/xAAYAAADAQEAAAAAAAAAAAAAAAAEBQYDAv/EAC8QAAIBAwEEBgsAAAAAAAAAAAECAwAEERIFITHREyJBUZHSQmFxcqGis8HC4eL/xAAWAQEBAQAAAAAAAAAAAAAAAAADBQT/xAAcEQABBQEBAQAAAAAAAAAAAAABAAIDBBESMSH/2gAMAwEAAhEDEQA/AEaKXYKoyTT3ZNqwEbadxKk596I863tNnR2i6nXU4Y4bvHXI+AXxoyKMjA07lyAB24P81TmsBx+eKXBWLRp9SraaYtIkIwUhXh6kNI6qrq06QPEAQSmAcZ9Fh9qn76ze3vZ4I1Z1jO4gcV7KWtID8Q2oyMKqxdrJGHAYjHAnOCM5HyGu+mQ565yD+uXjU3sraIhMcMpxGDz8xptaOkxQI2Sd/wBPzVjkr8nFuis9t1GS3CRRNMNTKE17txIwT+JoO429BaXEsBjlYxtpYqR1scuFY3coFrk8Gt8ge1G51OO7SOzucsxyT3mlgrNdvSGxae3OV//Z' 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /ccrma-mir/assets/images/home.JPG

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: /
github_username:  ccrma-mir
youtube_channel_id: /

# Name of the Author
author-name: CCRMA MIR
# URL for the Image of the Author
author-image: 'https://ccrma.stanford.edu/sites/default/files/ccrma%20at%20dusk.jpg'
# 60 Words About the Author
author-about: Covering the fundamentals and developments in Music Information Retrieval
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://ccrma-mir.github.io

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
#permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
